// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID             int32            `json:"id"`
	UserID         int32            `json:"user_id"`
	OrganizationID int32            `json:"organization_id"`
	Status         string           `json:"status"`
	RequestedAt    pgtype.Timestamp `json:"requested_at"`
}

type Organization struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Phno        []string    `json:"phno"`
	Email       []string    `json:"email"`
	Address     string      `json:"address"`
}

type User struct {
	ID               int32       `json:"id"`
	Name             string      `json:"name"`
	Email            string      `json:"email"`
	Gid              string      `json:"gid"`
	OrganizationID   pgtype.Int4 `json:"organization_id"`
	Role             pgtype.Text `json:"role"`
	OrganizationRole pgtype.Text `json:"organization_role"`
	Bdfl             pgtype.Bool `json:"bdfl"`
}
